CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    avatar VARCHAR(80),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    log_in VARCHAR(80) NOT NULL UNIQUE,
)
CREATE TABLE events {
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    event_name VARCHAR(255) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    start_time INT NOT NULL,
    end_time INT NOT NULL
}
CREATE TABLE event (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    event_id INT NOT NULL,
    FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
    user INT NOT NULL,
    FOREIGN KEY(user) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(event_id, user)
);